### ISSUE TITLE
NavBar view issue for scolling with smaller viewport

### ISSUE THREAD

**Issue by tangingw** [pycon-my/pycon-my.github.io#35]
The NavBar does not display Contact for iPhone 4 viewport while scrolling down
![image](https://github.com/pycon-my/pycon-my.github.io/assets/3361506/f6b1b2f6-55c0-4445-9a88-5cb2f70719c7)

While on the viewport for iPhone 12, the NavBar is visible upon scrolling
![image](https://github.com/pycon-my/pycon-my.github.io/assets/3361506/cdbf4099-b147-4cd9-b4ba-2935a1efce63)

**Comment by amirulabu** [comment]
Got 2 option


option 1 using modal from top
https://github.com/pycon-my/pycon-my.github.io/assets/10055534/55e816bf-2250-48ed-9357-81818e9f0f6a


Option 2 using menu, but it is scroll horizontal. (cannot make it scroll vertical due to default design choice by daisyUI)
https://github.com/pycon-my/pycon-my.github.io/assets/10055534/6304c410-f292-4ee7-b26f-942de884eba9
